//! Integer liquidity prorating with an overflow-free fallback, without a wide integer dependency.

use binsight_core::units::RawTokenAmount;

/// Floors `amount * share / supply`; invalid liquidity or arithmetic returns `None`.
pub(super) fn proportional_amount(
    amount: RawTokenAmount,
    share: u128,
    supply: u128,
) -> Option<RawTokenAmount> {
    if supply == 0 || share > supply {
        return None;
    }
    if let Some(product) = amount.0.checked_mul(share) {
        return Some(RawTokenAmount(product.checked_div(supply)?));
    }
    // Long division processes amount's bits. The remainder stays below supply; the quotient
    // stays below the processed prefix of amount because share <= supply.
    let mut quotient = 0_u128;
    let mut remainder = 0_u128;
    for bit in (0..u128::BITS).rev() {
        let (doubled, carry) = add_modulo(remainder, remainder, supply)?;
        remainder = doubled;
        quotient = quotient.checked_mul(2)?.checked_add(carry)?;
        if amount.0.checked_shr(bit)? & 1 != 0 {
            let (added, carry) = add_modulo(remainder, share, supply)?;
            remainder = added;
            quotient = quotient.checked_add(carry)?;
        }
    }
    Some(RawTokenAmount(quotient))
}

fn add_modulo(remainder: u128, addend: u128, modulus: u128) -> Option<(u128, u128)> {
    let room = modulus.checked_sub(remainder)?;
    if addend >= room {
        Some((addend.checked_sub(room)?, 1))
    } else {
        Some((remainder.checked_add(addend)?, 0))
    }
}

#[cfg(test)]
#[expect(
    clippy::arithmetic_side_effects,
    reason = "oracle products of u64 fit u128; nonzero supply and subtractions are bounded by test invariants"
)]
mod tests {
    use proptest::prelude::*;

    use super::*;

    #[test]
    fn matches_python_unbounded_integer_oracles_at_wide_boundaries() {
        // Independently generated by Python's amount * share // supply, not by this algorithm.
        let cases: Vec<[String; 4]> = serde_json::from_str(include_str!(
            "../../tests/fixtures/math/proportional-amounts.json"
        ))
        .unwrap();
        for [amount, share, supply, expected] in cases {
            assert_eq!(
                proportional_amount(
                    RawTokenAmount(amount.parse().unwrap()),
                    share.parse().unwrap(),
                    supply.parse().unwrap()
                ),
                Some(RawTokenAmount(expected.parse().unwrap())),
            );
        }
    }

    #[test]
    fn refuses_zero_supply_and_excess_shares() {
        assert_eq!(proportional_amount(RawTokenAmount(1), 0, 0), None);
        assert_eq!(proportional_amount(RawTokenAmount(1), 2, 1), None);
    }

    proptest! {
        #[test]
        fn equals_direct_integer_division_when_the_product_fits(amount: u64, share: u64, rest: u64) {
            let supply = u128::from(share) + u128::from(rest) + 1;
            let expected = u128::from(amount) * u128::from(share) / supply;
            prop_assert_eq!(proportional_amount(RawTokenAmount(u128::from(amount)), u128::from(share), supply), Some(RawTokenAmount(expected)));
        }

        #[test]
        fn conserves_a_balance_split_between_two_positions(amount: u128, supply in 1_u128..=u128::MAX, fraction: u128) {
            let share = fraction % supply;
            let remainder = supply - share;
            let first = proportional_amount(RawTokenAmount(amount), share, supply).unwrap().0;
            let second = proportional_amount(RawTokenAmount(amount), remainder, supply).unwrap().0;
            let combined = first.checked_add(second).unwrap();
            prop_assert!(combined <= amount);
            prop_assert!(amount - combined <= 1);
        }
    }
}
