[package]
name = "binsight-solana"
description = "Solana primitives without any network access."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
bs58.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
